###
GET http://localhost:4000/api/bank_account/c0fa7172-4b8a-4836-9b18-1e2db3656448

###
GET http://localhost:4000/api/bank_account/c0fa7172-4b8a-4836-9b18-1e2db3656448/transactions

###

POST http://localhost:4000/api/bank_account/open
content-type: application/json

{
    "account_number": "A123456",
    "initial_balance": 0,
    "status": "active"
}

###

POST http://localhost:4000/api/bank_account/status
content-type: application/json

{
    "id": "c0fa7172-4b8a-4836-9b18-1e2db3656448",
    "status": "active"
}

###

POST http://localhost:4000/api/bank_account/deposit
content-type: application/json

{
    "id": "c0fa7172-4b8a-4836-9b18-1e2db3656448",
    "amount": 200
}

###

POST http://localhost:4000/api/bank_account/withdraw
content-type: application/json

{
    "id": "c0fa7172-4b8a-4836-9b18-1e2db3656448",
    "amount": 100
}
